### PR TITLE
fix(): added filter section and implemented it's functionality

### PR DESCRIPTION
**Pull request by Satyakoidala**
Hi @sceary-expert,

Implemented filter section. Please follow through with the function implementations and see the comments for the docs.

**MAJOR CHANGES:**
1.  Implemented `filter` section.
2. Added JS `functionalities` to improve re-usability.

### CODE REVIEW

**Comment by onnhyd** [comment]
> Hi @sceary-expert,
> 
> Implemented filter section. Please follow through with the function implementations and see the comments for the docs.
> 
> **MAJOR CHANGES:**
> 
> 1. Implemented `filter` section.
> 2. Added JS `functionalities` to improve re-usability.

Looks Good to me just sync your fork otherwise it's creating conflict as recent changes has been made.

**Comment by Satyakoidala** [comment]
> > Hi @sceary-expert,
> > Implemented filter section. Please follow through with the function implementations and see the comments for the docs.
> > **MAJOR CHANGES:**
> > 
> > 1. Implemented `filter` section.
> > 2. Added JS `functionalities` to improve re-usability.
> 
> Looks Good to me just sync your fork otherwise it's creating conflict as recent changes has been made.

Fixed Merge conflicts. Please review it.

**Review by onnhyd — APPROVED** [review]

**Comment by Satyakoidala** [comment]
Hi @sceary-expert,

Please add hacktoberfest accepted label. Thanks!

**Comment by onnhyd** [comment]
> Hi @sceary-expert,
> 
> Please add hacktoberfest accepted label. Thanks!

Is it not showing in the Lables section? I have added already

**Comment by Satyakoidala** [comment]
> > Hi @sceary-expert,
> > Please add hacktoberfest accepted label. Thanks!
> 
> Is it not showing in the Lables section? I have added already

Thanks for taking the time. It's being shown now.

**Pull request merged**
